# Basic Pytoch - Word Embeddings with Deep Learning

In [0]:
# NVIDIA profiling tool for the available GPU
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148


In [0]:
!nvidia-smi

Sun Jan 27 06:06:43 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8    30W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [0]:
# CLone my repo that contains the shell file
!git clone https://gist.github.com/f7b7c7758a46da49f84bc68b47997d69.git

Cloning into 'f7b7c7758a46da49f84bc68b47997d69'...
remote: Enumerating objects: 16, done.
remote: Total 16 (delta 0), reused 0 (delta 0), pack-reused 16
Unpacking objects: 100% (16/16), done.


In [0]:
# Move to te directory where the file was donwloaded
cd f7b7c7758a46da49f84bc68b47997d69/

/content/f7b7c7758a46da49f84bc68b47997d69


In [0]:
# Execute the shell script. 
# NOTE: This takes sometime and it breaks the connection. Better use the steps after and execute them one by one.

#!bash pytorch041_cuda92_colab.sh

In [0]:
!wget https://developer.nvidia.com/compute/cuda/9.2/Prod2/local_installers/cuda-repo-ubuntu1604-9-2-local_9.2.148-1_amd64

--2019-01-27 06:07:15--  https://developer.nvidia.com/compute/cuda/9.2/Prod2/local_installers/cuda-repo-ubuntu1604-9-2-local_9.2.148-1_amd64
Resolving developer.nvidia.com (developer.nvidia.com)... 192.229.162.216
Connecting to developer.nvidia.com (developer.nvidia.com)|192.229.162.216|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.download.nvidia.com/compute/cuda/9.2/secure/Prod2/local_installers/cuda-repo-ubuntu1604-9-2-local_9.2.148-1_amd64.deb?UMU2C4btU2wXIkcr0Cq3vfPXFLxUJoPA0wnw8zgYkoMB4Sz8xo5-VTXhhIIp6r82jor_ePKFseHh3OHMU-ueWQQUsJgV1rI_R-5jQp-EiLsh13kYQIWrb2s0ssvtmM5CYFNCYtr8ulEv_9dUKS9YdTVS15qbUrQvPodLurYx_zQjNuHXuJBZlvzZFDSHB58Ks2cU7duqeCGa86NwxpVCog [following]
--2019-01-27 06:07:16--  https://developer.download.nvidia.com/compute/cuda/9.2/secure/Prod2/local_installers/cuda-repo-ubuntu1604-9-2-local_9.2.148-1_amd64.deb?UMU2C4btU2wXIkcr0Cq3vfPXFLxUJoPA0wnw8zgYkoMB4Sz8xo5-VTXhhIIp6r82jor_ePKFseHh3OHMU-ueWQQUsJgV1rI_R-5jQp-EiLsh1

In [0]:
!dpkg --install cuda-repo-ubuntu1604-9-2-local_9.2.148-1_amd64

Selecting previously unselected package cuda-repo-ubuntu1604-9-2-local.
(Reading database ... 110851 files and directories currently installed.)
Preparing to unpack cuda-repo-ubuntu1604-9-2-local_9.2.148-1_amd64 ...
Unpacking cuda-repo-ubuntu1604-9-2-local (9.2.148-1) ...
Setting up cuda-repo-ubuntu1604-9-2-local (9.2.148-1) ...


In [0]:
!apt-key add /var/cuda-repo-9-2-local/7fa2af80.pub

OK


In [0]:
!apt-get update

Get:1 file:/var/cuda-repo-9-2-local  InRelease
Ign:1 file:/var/cuda-repo-9-2-local  InRelease
Get:2 file:/var/cuda-repo-9-2-local  Release [574 B]
Get:2 file:/var/cuda-repo-9-2-local  Release [574 B]
Get:3 file:/var/cuda-repo-9-2-local  Release.gpg [819 B]
Get:3 file:/var/cuda-repo-9-2-local  Release.gpg [819 B]
Get:4 file:/var/cuda-repo-9-2-local  Packages [18.7 kB]
Hit:5 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:6 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease [21.3 kB]
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:8 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1710/x86_64  InRelease
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Ign:10 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  InRelease
Hit:11 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1710/x86_64  Release
Hit:12 https://developer.download.nvidia.com/compu

In [0]:
# NOTE: This might take some time..
!apt-get install cuda

Reading package lists... Done
Building dependency tree       
Reading state information... Done
cuda is already the newest version (9.2.148-1).
0 upgraded, 0 newly installed, 0 to remove and 72 not upgraded.


In [0]:
# Check the version of CUDA on the system
!cat /usr/local/cuda/version.txt

CUDA Version 9.2.148


In [0]:
!pip install http://download.pytorch.org/whl/cu92/torch-0.4.1-cp36-cp36m-linux_x86_64.whl

    100% |████████████████████████████████| 512.6MB 34.3MB/s 
tcmalloc: large alloc 1073750016 bytes == 0x58922000 @  0x7f8cb8da52a4 0x591a07 0x5b5d56 0x502e9a 0x506859 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x504c28 0x502540 0x502f3d 0x507641
torchvision 0.2.1 has requirement pillow>=4.1.1, but you'll have pillow 4.0.0 which is incompatible.
fastai 1.0.41 has requirement torch>=1.0.0, but you'll have torch 0.4.1 which is incompatible.
  Found existing installation: torch 1.0.0
    Uninstalling torch-1.0.0:
      Successfully uninstalled torch-1.0.0


In [0]:
!pip install torchvision

    100% |████████████████████████████████| 2.0MB 11.0MB/s 
fastai 1.0.41 has requirement torch>=1.0.0, but you'll have torch 0.4.1 which is incompatible.
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0
  [PIL]
You must restart the runtime in order to use newly installed versions.


In [0]:
import torch

print("PyTorch version: ")
print(torch.__version__)
print("CUDA Version: ")
print(torch.version.cuda)
print("cuDNN version is: ")
print(torch.backends.cudnn.version())

PyTorch version: 
1.0.0
CUDA Version: 
9.0.176
cuDNN version is: 
7401


# **Basic examples of NLP with PyTorch**


In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

## Basic Word Embedding

In [0]:
word_to_ix = {"hello": 0, "world": 1, "!": 2}
embeds = nn.Embedding(3, 5)  # 3 words in vocab, 5 dimensional embeddings
lookup_tensor = torch.tensor([word_to_ix["hello"]], dtype=torch.long)
hello_embed = embeds(lookup_tensor)
print(hello_embed)

tensor([[ 0.6614,  0.2669,  0.0617,  0.6213, -0.4519]],
       grad_fn=<EmbeddingBackward>)


In [0]:
lookup_tensor = torch.tensor([word_to_ix["hello"]], dtype=torch.long)
hello_embed = embeds(lookup_tensor)
lookup_tensor = torch.tensor([word_to_ix["world"]], dtype=torch.long)
world_embed = embeds(lookup_tensor)
token_tensor = torch.tensor([word_to_ix["!"]], dtype=torch.long)
token_embed = embeds(token_tensor)
array_test = [hello_embed, world_embed, token_embed]
print(type(array_test))
array_tensor = torch.stack(array_test)
sum_token = torch.mean(array_tensor, keepdim=True, dim=0 )
print(hello_embed)
print(world_embed)
print(token_embed)
print(token_embed.size())
print(array_tensor)
print(array_tensor.size())

print(sum_token)


<class 'list'>
tensor([[ 0.6614,  0.2669,  0.0617,  0.6213, -0.4519]],
       grad_fn=<EmbeddingBackward>)
tensor([[-0.1661, -1.5228,  0.3817, -1.0276, -0.5631]],
       grad_fn=<EmbeddingBackward>)
tensor([[-0.8923, -0.0583, -0.1955, -0.9656,  0.4224]],
       grad_fn=<EmbeddingBackward>)
torch.Size([1, 5])
tensor([[[ 0.6614,  0.2669,  0.0617,  0.6213, -0.4519]],

        [[-0.1661, -1.5228,  0.3817, -1.0276, -0.5631]],

        [[-0.8923, -0.0583, -0.1955, -0.9656,  0.4224]]],
       grad_fn=<StackBackward>)
torch.Size([3, 1, 5])
tensor([[[-0.1324, -0.4380,  0.0826, -0.4573, -0.1975]]],
       grad_fn=<MeanBackward0>)


## N-Gram Language Modeling

In [0]:
CONTEXT_SIZE = 2
EMBEDDING_DIM = 10
# We will use Shakespeare Sonnet 2
test_sentence = """When forty winters shall besiege thy brow,
And dig deep trenches in thy beauty's field,
Thy youth's proud livery so gazed on now,
Will be a totter'd weed of small worth held:
Then being asked, where all thy beauty lies,
Where all the treasure of thy lusty days;
To say, within thine own deep sunken eyes,
Were an all-eating shame, and thriftless praise.
How much more praise deserv'd thy beauty's use,
If thou couldst answer 'This fair child of mine
Shall sum my count, and make my old excuse,'
Proving his beauty by succession thine!
This were to be new made when thou art old,
And see thy blood warm when thou feel'st it cold.""".split()

In [0]:
trigrams = [([test_sentence[i], test_sentence[i + 1]], test_sentence[i + 2])
            for i in range(len(test_sentence) - 2)]
# print the first 3, just so you can see what they look like
print(trigrams[:3])

[(['When', 'forty'], 'winters'), (['forty', 'winters'], 'shall'), (['winters', 'shall'], 'besiege')]


In [0]:
vocab = set(test_sentence)
word_to_ix = {word: i for i, word in enumerate(vocab)}

In [0]:
class NGramLanguageModeler(nn.Module):

    def __init__(self, vocab_size, embedding_dim, context_size):
        super(NGramLanguageModeler, self).__init__()
        self.embeddings = nn.Embedding(vocab_size, embedding_dim)
        self.linear1 = nn.Linear(context_size * embedding_dim, 128)
        self.linear2 = nn.Linear(128, vocab_size)

    def forward(self, inputs):
        embeds = self.embeddings(inputs).view((1, -1))
        out = F.relu(self.linear1(embeds))
        out = self.linear2(out)
        log_probs = F.log_softmax(out, dim=1)
        return log_probs

In [0]:
losses = []
loss_function = nn.NLLLoss()
model = NGramLanguageModeler(len(vocab), EMBEDDING_DIM, CONTEXT_SIZE)
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [0]:
n_epoch = 100
for epoch in range(n_epoch):
    total_loss = 0
    for context, target in trigrams:

        # Step 1. Prepare the inputs to be passed to the model (i.e, turn the words
        # into integer indices and wrap them in tensors)
        context_idxs = torch.tensor([word_to_ix[w] for w in context], dtype=torch.long)

        # Step 2. Recall that torch *accumulates* gradients. Before passing in a
        # new instance, you need to zero out the gradients from the old
        # instance
        model.zero_grad()

        # Step 3. Run the forward pass, getting log probabilities over next
        # words
        log_probs = model(context_idxs)

        # Step 4. Compute your loss function. (Again, Torch wants the target
        # word wrapped in a tensor)
        loss = loss_function(log_probs, torch.tensor([word_to_ix[target]], dtype=torch.long))

        # Step 5. Do the backward pass and update the gradient
        loss.backward()
        optimizer.step()

        # Get the Python number from a 1-element Tensor by calling tensor.item()
        total_loss += loss.item()
    print("epoch(%d) loss: %f"%(epoch, total_loss))
    losses.append(total_loss)

epoch(0) loss: 522.334395
epoch(1) loss: 519.845836
epoch(2) loss: 517.373542
epoch(3) loss: 514.916929
epoch(4) loss: 512.475893
epoch(5) loss: 510.050383
epoch(6) loss: 507.639275
epoch(7) loss: 505.242038
epoch(8) loss: 502.857359
epoch(9) loss: 500.485287
epoch(10) loss: 498.124641
epoch(11) loss: 495.775747
epoch(12) loss: 493.437327
epoch(13) loss: 491.108869
epoch(14) loss: 488.789346
epoch(15) loss: 486.476932
epoch(16) loss: 484.171072
epoch(17) loss: 481.870793
epoch(18) loss: 479.576999
epoch(19) loss: 477.287404
epoch(20) loss: 475.003558
epoch(21) loss: 472.724062
epoch(22) loss: 470.447245
epoch(23) loss: 468.173134
epoch(24) loss: 465.900571
epoch(25) loss: 463.631922
epoch(26) loss: 461.366170
epoch(27) loss: 459.101134
epoch(28) loss: 456.838301
epoch(29) loss: 454.576596
epoch(30) loss: 452.316368
epoch(31) loss: 450.055780
epoch(32) loss: 447.796130
epoch(33) loss: 445.535799
epoch(34) loss: 443.274056
epoch(35) loss: 441.012017
epoch(36) loss: 438.746049
epoch(37) l

## Continuous Bag of Words

In [0]:
CONTEXT_SIZE = 2  # 2 words to the left, 2 to the right
raw_text = """We are about to study the idea of a computational process.
Computational processes are abstract beings that inhabit computers.
As they evolve, processes manipulate other abstract things called data.
The evolution of a process is directed by a pattern of rules
called a program. People create programs to direct processes. In effect,
we conjure the spirits of the computer with our spells.""".split()

# By deriving a set from `raw_text`, we deduplicate the array
vocab = set(raw_text)
vocab_size = len(vocab)

word_to_ix = {word: i for i, word in enumerate(vocab)}
data = []
for i in range(2, len(raw_text) - 2):
    context = [raw_text[i - 2], raw_text[i - 1],
               raw_text[i + 1], raw_text[i + 2]]
    target = raw_text[i]
    data.append((context, target))
print("Vocab size: %d"%vocab_size)
print(data[0])
print(data[1])
print(data[2])
print(data[3])
print(data[4])

Vocab size: 49
(['We', 'are', 'to', 'study'], 'about')
(['are', 'about', 'study', 'the'], 'to')
(['about', 'to', 'the', 'idea'], 'study')
(['to', 'study', 'idea', 'of'], 'the')
(['study', 'the', 'of', 'a'], 'idea')


In [0]:
print(word_to_ix)

{'conjure': 0, 'effect,': 1, 'to': 2, 'things': 3, 'pattern': 4, 'idea': 5, 'program.': 6, 'they': 7, 'are': 8, 'spells.': 9, 'our': 10, 'data.': 11, 'People': 12, 'The': 13, 'direct': 14, 'by': 15, 'evolution': 16, 'computational': 17, 'that': 18, 'programs': 19, 'spirits': 20, 'directed': 21, 'with': 22, 'study': 23, 'of': 24, 'process': 25, 'the': 26, 'other': 27, 'inhabit': 28, 'is': 29, 'rules': 30, 'beings': 31, 'computer': 32, 'abstract': 33, 'computers.': 34, 'In': 35, 'As': 36, 'a': 37, 'processes': 38, 'process.': 39, 'create': 40, 'processes.': 41, 'Computational': 42, 'we': 43, 'called': 44, 'manipulate': 45, 'evolve,': 46, 'about': 47, 'We': 48}


In [0]:
print(data)

[(['We', 'are', 'to', 'study'], 'about'), (['are', 'about', 'study', 'the'], 'to'), (['about', 'to', 'the', 'idea'], 'study'), (['to', 'study', 'idea', 'of'], 'the'), (['study', 'the', 'of', 'a'], 'idea'), (['the', 'idea', 'a', 'computational'], 'of'), (['idea', 'of', 'computational', 'process.'], 'a'), (['of', 'a', 'process.', 'Computational'], 'computational'), (['a', 'computational', 'Computational', 'processes'], 'process.'), (['computational', 'process.', 'processes', 'are'], 'Computational'), (['process.', 'Computational', 'are', 'abstract'], 'processes'), (['Computational', 'processes', 'abstract', 'beings'], 'are'), (['processes', 'are', 'beings', 'that'], 'abstract'), (['are', 'abstract', 'that', 'inhabit'], 'beings'), (['abstract', 'beings', 'inhabit', 'computers.'], 'that'), (['beings', 'that', 'computers.', 'As'], 'inhabit'), (['that', 'inhabit', 'As', 'they'], 'computers.'), (['inhabit', 'computers.', 'they', 'evolve,'], 'As'), (['computers.', 'As', 'evolve,', 'processes']

In [0]:
def make_context_vector(context, word_to_ix):
  idxs = [word_to_ix[w] for w in context]
  return torch.tensor(idxs, dtype=torch.long)

make_context_vector(data[0][0], word_to_ix)

tensor([48,  8,  2, 23])

In [0]:
data_train = [(make_context_vector(x_word, word_to_ix), word_to_ix[y_word]) 
              for x_word, y_word in data]

In [0]:
embedding_dim = 110

In [0]:
class CBOW(nn.Module):
  
  def __init__(self, vocab_size, embedding_dim, context_size):
    super(CBOW, self).__init__()
    self.context_size = context_size
    self.embeddings = nn.Embedding(vocab_size, embedding_dim)
    self.linear1 = nn.Linear(embedding_dim, 128)
    self.linear2 = nn.Linear(128, vocab_size)
    
  def forward(self, inputs):
    embeds = self.embeddings(inputs).view((self.context_size*2, embedding_dim))
    hidden1_mean = torch.mean(embeds, keepdim=True, dim=0)
    z1 = self.linear1(hidden1_mean)
    z2 = self.linear2(z1)
    y_pred = F.log_softmax(z2, dim=1)
    return y_pred
    

In [0]:
loss_function = nn.NLLLoss()
model = CBOW(vocab_size, embedding_dim, CONTEXT_SIZE)
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [0]:
n_epoch = 100

In [0]:
for epoch in range(n_epoch):
  total_loss = 0
  for xs_ids, y_id in data_train:
    model.zero_grad()
    y_pred = model(xs_ids)
    loss = loss_function(y_pred, torch.tensor([y_id], dtype=torch.long))
    
    loss.backward()
    optimizer.step()
    
    total_loss += loss.item()
  print("epoch (%s/%s): %f"%(epoch, n_epoch, total_loss))

epoch (0/100): 224.768022
epoch (1/100): 185.773384
epoch (2/100): 150.560980
epoch (3/100): 115.242117
epoch (4/100): 83.091576
epoch (5/100): 56.674554
epoch (6/100): 37.572915
epoch (7/100): 25.064697
epoch (8/100): 17.234778
epoch (9/100): 12.344531
epoch (10/100): 9.208761
epoch (11/100): 7.116354
epoch (12/100): 5.661807
epoch (13/100): 4.612602
epoch (14/100): 3.831340
epoch (15/100): 3.233698
epoch (16/100): 2.765981
epoch (17/100): 2.392781
epoch (18/100): 2.089996
epoch (19/100): 1.840802
epoch (20/100): 1.633118
epoch (21/100): 1.458138
epoch (22/100): 1.309261
epoch (23/100): 1.181510
epoch (24/100): 1.071034
epoch (25/100): 0.974828
epoch (26/100): 0.890526
epoch (27/100): 0.816235
epoch (28/100): 0.750426
epoch (29/100): 0.691846
epoch (30/100): 0.639482
epoch (31/100): 0.592476
epoch (32/100): 0.550126
epoch (33/100): 0.511846
epoch (34/100): 0.477118
epoch (35/100): 0.445531
epoch (36/100): 0.416724
epoch (37/100): 0.390379
epoch (38/100): 0.366219
epoch (39/100): 0.344

## **References** 
* Word Embeddings: Encoding Lexical Semantics, Part I https://pytorch.org/tutorials/beginner/nlp/word_embeddings_tutorial.html#sphx-glr-beginner-nlp-word-embeddings-tutorial-py 
* TORCH.OPTIM https://pytorch.org/docs/stable/optim.html
